<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>_cvv</name>
   <tag></tag>
   <elementGuidId>f55b98e6-3db5-4c81-af6a-ec4e3c9b62e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;application&quot;]/div[3]/div/div/div/form/div[2]/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;application&quot;]/div[3]/div/div/div/form/div[2]/div[3]/input</value>
   </webElementProperties>
</WebElementEntity>
